### PR TITLE
Relative start position / Reduce angle on direction

### PR DESCRIPTION
**Pull request by icedocemile**
- Applying relative neutral position on axis Y while taping on "Start flying" (Wings stopped on start flying phone position )
- Reduce angle range to get max value on direction -> Easier to get the max angle.
- decreasing refresh frequency a little

### CODE REVIEW

**Comment by icedocemile** [comment]
Two ways of coding :) In complex algorithm, a "return" in the middle of the code could be difficult to find/understand.

**Comment by fahhem** [comment]
It's not in the middle, it's at the top, a common theme 'early return'.

**Comment by icedocemile** [comment]
I was talking in general ; this is how I used to code because of that reason. If you work with a developer team, you'll see that each of one has his own style with any reason to do that :)
But I do understand your remark.

**Comment by fahhem** [comment]
I'm used to more in-depth code reviews, but this isn't an actual product. Sorry for giving you a hard time!

**Pull request merged**
